# Apply to all files without commiting:
#   pre-commit run --all-files
repos:
#  - repo: local
#    hooks:
#      - id: pytest-check
#        name: pytest-check
#        entry: bash -c 'poetry run pytest tests/'
#        language: system
#        pass_filenames: false
#        always_run: true
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: README.md, assets/
      - id: trailing-whitespace
      - id: flake8
        additional_dependencies:
          [
            flake8==4.0.1,
            flake8-bugbear==21.11.29,
            flake8-builtins==1.5.3,
            flake8-comprehensions==3.7.0,
            flake8-docstrings==1.6.0,
            flake8-import-order==0.18.1,
            flake8-tidy-imports==4.5.0,
          ]
      - id: requirements-txt-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.13.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
