# Apply to all files without commiting:
#   pre-commit run --all-files
exclude: ^(src/caracal/typesparser/|tutorials)
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=79]
        additional_dependencies: ['click==8.1.3']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
        exclude: ^(src/caracal/typesparser/|tutorials)
        args: ["--config=setup.cfg"]
        additional_dependencies:
          [
            flake8-bugbear==20.1.4,
            flake8-builtins==1.5.3,
            flake8-comprehensions==3.2.3,
            flake8-docstrings==1.5.0,
            flake8-import-order==0.18.1,
            flake8-tidy-imports==4.1.0,
            flake8==3.8.3,
            flake8-black>=0.1.1,
          ]
      - id: requirements-txt-fixer
